yolo_model:

  config_file:
    name: yolov3-tiny_n.cfg
  weight_file:
    name: yolov3-tiny_n_50000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - corn
      - wheat
      - cucumber
      - rice
      - corn_1
      - corn_2
      - cucumber_1
      - cucumber_2
      - cucumber_3
      - watermelon