yolo_model:

  config_file:
    name: yolov3-voc.cfg
  weight_file:
    name: yolov3-voc-6700.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - tableware
      - pet
      - bed
      - television
      - person
      - sofa
      - food
      - table/chair

