# obstacle_layer:配置障碍物图层

    # enabled:是否启用该层

    # combination_method:只能设置为0或1，用来更新地图上的代价值，一般设置为1;

    # track_unknown_space:如果设置为false，那么地图上代价值就只分为致命碰撞和自由区域两种，如果设置为true，那么就分为致命碰撞，自由区域和未知区域三种。意思是说假如该参数设置为false的话，就意味着地图上的未知区域也会被认为是可以自由移动的区域，这样在进行全局路径规划时，可以把一些未探索的未知区域也来参与到路径规划，如果你需要这样的话就将该参数设置为false。不过一般情况未探索的区域不应该当作可以自由移动的区域，因此一般将该参数设置为true;

    # obstacle_range:设置机器人检测障碍物的最大范围，意思是说超过该范围的障碍物，并不进行检测，只有靠近到该范围内才把该障碍物当作影响路径规划和移动的障碍物;雷达物理限制0.1-16m

    # raytrace_range:在机器人移动过程中，实时清除代价地图上的障碍物的最大范围，更新可自由移动的空间数据。假如设置该值为3米，那么就意味着在3米内的障碍物，本来开始时是有的，但是本次检测却没有了，那么就需要在代价地图上来更新，将旧障碍物的空间标记为可以自由移动的空间。

    # observation_sources:设置导航中所使用的传感器，这里可以用逗号形式来区分开很多个传感器，例如激光雷达，碰撞传感器，超声波传感器等，我们这里只设置了激光雷达;

    # laser_scan_sensor:添加的激光雷达传感器

    # sensor_frame:激光雷达传感器的坐标系名称;

    # data_type:激光雷达数据类型;

    # topic:该激光雷达发布的话题名;

    # marking:是否可以使用该传感器来标记障碍物;

    # clearing:是否可以使用该传感器来清除障碍物标记为自由空间;

    # inflation_layer:膨胀层，用于在障碍物外标记一层危险区域，在路径规划时需要避开该危险区域

    # enabled:是否启用该层;

    # cost_scaling_factor:膨胀过程中应用到代价值的比例因子，代价地图中到实际障碍物距离在内切圆半径到膨胀半径之间的所有cell可以使用如下公式来计算膨胀代价： [e^(-x*r)*264 ]exp(-1.0 * cost_scaling_factor * (distance_from_obstacle – inscribed_radius)) * (costmap_2d::INSCRIBED_INFLATED_OBSTACLE – 1),公式中costmap_2d::INSCRIBED_INFLATED_OBSTACLE目前指定为254，注意： 由于在公式中cost_scaling_factor被乘了一个负数，所以增大比例因子反而会降低代价

    # inflation_radius:膨胀半径，膨胀层会把障碍物代价膨胀直到该半径为止，一般将该值设置为机器人底盘的直径大小。

 

    # Static_layer:静态地图层，即SLAM中构建的地图层

    # enabled:是否启用该地图层

# footprint: [[0.171, -0.128], [0.171, 0.128],[-0.171, 0.128], [-0.171, -0.128]]
#0.128
#footprint: [ [-0.15,-0.12], [0.15,-0.12], [0.15,0.12], [-0.15,0.12] ]
#footprint: [ [-0.14,-0.11], [0.14,-0.11], [0.14,0.11], [-0.14,0.11] ]
#footprint: [ [-0.13,-0.09], [0.13,-0.09], [0.13,0.09], [-0.13,0.09] ]
robot_radius: 0.13
obstacle_range: 2.5 #4.0
raytrace_range: 3 #4.5

inflation_layer:
  enabled: true
  inflation_radius: 0.30 #0.35
  cost_scaling_factor: 35  #35

obstacle_layer:
  enabled: true
  track_unknown_space: false
  combination_method: 1

  obstacle_range: 2.5  #4.0
  raytrace_range: 3   #4.5

  observation_sources: scan
  scan: {
    data_type: LaserScan,
    topic: /scan,
    marking: true,
    clearing: true
  }