#Robot Configuration Parameters机器人配置参数.
acc_lim_x: 2.5 #x方向的加速度绝对值.
acc_lim_y: 2.5 #y方向的加速度绝对值,该值只有全向移动的机器人才需配置.
acc_lim_th: 3.2 #旋转加速度的绝对值.
max_trans_vel: 3 #平移速度最大值绝对值.
min_trans_vel: 0.1 #平移速度最小值的绝对值.
max_vel_x: 2 #x方向最大速度的绝对值.
min_vel_x: -1 #x方向最小值绝对值,如果为负值表示可以后退.
max_vel_y: 2 #y方向最大速度的绝对值.
min_vel_y: 0 #y方向最小速度的绝对值.
max_rot_vel: 2.0 #最大旋转速度的绝对值.
min_rot_vel: -2.0 #最小旋转速度的绝对值.
#Goal Tolerance Parameters目标公差参数.
yaw_goal_tolerance: 0.05 #到达目标点时偏行角允许的误差，单位弧度.
xy_goal_tolerance: 0.10 #到达目标点时,在xy平面内与目标点的距离误差.
latch_xy_goal_tolerance:  false #设置为true,如果到达容错距离内,机器人就会原地旋转,即使转动是会跑出容错距离外.
#Forward Simulation Parameters正向仿真参数.
sim_time: 10 #向前仿真轨迹的时间.
sim_granularity: 0.2 #步长,轨迹上采样点之间的距离,轨迹上点的密集程度.step_size=(max-min)/(nums_samples-1) 
vx_samples: 100 #x方向速度空间的采样点数.
vy_samples: 100 #y方向速度空间采样点数.
vth_samples: 100 #旋转方向的速度空间采样点数.
controller_frequency: 20.0 #发送给底盘控制移动指令的频率.
#Trajectory Scoring Parameters轨迹评分参数.
path_distance_bias: 100.0 #定义控制器与给定路径接近程度的权重.
goal_distance_bias: 24.0 #定义控制器与局部目标点的接近程度的权重.
occdist_scale: 100 #定义控制器躲避障碍物的程度.
forward_point_distance: 2 #距离机器人中心点的距离，以米为单位放置额外的得分点.
stop_time_buffer: 1 #为防止碰撞,机器人必须提前停止的时间长度.
scaling_speed: 2 #启动机器人底盘的速度.
max_scaling_factor: 0.2 #最大缩放参数.
publish_cost_grid: false #是否发布规划器在规划路径时的代价网格.如果设置为true,那么就会在~/cost_cloud话题上发布sensor_msgs/PointCloud2类型消息.
#Oscillation Prevention Parameters防振荡参数.
oscillation_reset_dist: 0.05 #机器人运动多远距离才会重置振荡标记.
#Global Plan Parameters全局计划参数.
prune_plan: true #机器人前进是是否清除身后1m外的轨迹
